version: '3.8'

services:
  storeapp:
    image: computer_store
    container_name: computer_store
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/computerstore?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.properties.hibernate.show_sql=true

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.25
    platform: linux/x86_64
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=computerstore
      - MYSQL_PASSWORD=root
    volumes:
       - ./mysql:/docker-entrypoint-initdb.d/:ro

networks:
  mynetwork:


