version: '20.10.20'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  marketapp:
    image: marketapp:0.0.1
    ports:
    - 9091:8080
    environment:
        DB_URL: "jdbc:h2:tcp://h2db/marketapp-db;DB_CLOSE_DELAY=-1"
        DB_USERNAME: "sa"
        DB_PASSWORD: "as"

  h2db:
    image: buildo/h2database/latest
    ports:
      - 9092:8082
