version: '3.8'

services:
  storeapp:
    image: computer_store
    container_name: computer_store
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/computer_store
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: as

    depends_on:
      h2db:
          condition: service_healthy
    command: ["/wait-for-it.sh", "h2db:1521", "--", "java", "-jar", "app.jar"]

  h2db:
    image: buildo/h2database:latest
    restart: always
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD", "nc", "-z","localhost", "1521" ]
      interval: 5s
      timeout: 10s
      retries: 10

    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./docker-entrypoint-initdb.d/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql


  redis:
    image: redis:latest
    ports:
      - "6379:6379"