version: '3.8'

services:
  marketapp:
    image: computer_store
    container_name: computer_store
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2:latest
    volumes:
      - ./docker-entrypoint-initdb.d/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql